apiVersion: apps.kubernetes.io/v1
kind: Headroom
metadata:
  name: nodes
spec:
  replicas: 3
  satisfiedBy:
    matchFields:
      - key: metadata.name
        operator: Exists
      - key: metadata.namespace
        operator: Exists
  template:
    metadata:
      labels:
        headroom: nodes
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: m5.large
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              headroom: nodes
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                headroom: nodes