# Represent static capacity for nodes by selecting against all pods
# using the satisfiedBy field. podAntiAffinity and topologySpreadConstraints are used to 
# request 3 m5.large instances spread across zones
apiVersion: apps.kubernetes.io/v1
kind: Headroom
metadata:
  name: nodes
  namespace: default
spec:
  replicas: 3
  satisfiedBy:
    matchFields:
      - key: metadata.name
        operator: Exists
      - key: metadata.namespace
        operator: Exists
  template:
    metadata:
      labels:
        headroom: nodes
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: m5.large
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              headroom: nodes
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                headroom: nodes
status:
  conditions:
    - type: CapacityAvailable
      status: True
      reason: CapacityAvailable
      message: ""
    - type: Ready
      status: True
      reason: Ready
      message: ""