# Represent static capacity for pods by selecting against specific pods to fill-up
# the capacity. The capacity is marked as available when a scheduling simulation sees that all of the pods
# in PodHeadroom have been successfully simulated pods would be eligible for scheduling
apiVersion: apps.kubernetes.io/v1
kind: PodHeadroom
metadata:
  name: nodes
  namespace: default
spec:
  replicas: 3
  satisfiedBy:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        headroom: pods
    spec:
      containers:
        - cpu: 1
          memory: 1Gi
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              headroom: pods
status:
  conditions:
    - type: CapacityAvailable
      status: True
      reason: CapacityAvailable
      message: ""
    - type: Ready
      status: True
      reason: Ready
      message: ""